name: 'Publish Container Image'
description: 'Publishes a container image to GitHub Packages.'
inputs:
  image-name:
    required: true
    description: 'The name of the container image.'
  github-token:
    required: true
    description: 'The value of secrets.GITHUB_TOKEN to publish the image to GitHub Packages.'
  docker-context:
    required: false
    default: '.'
    description: 'The working directory where docker build is called from.'
  dockerfile-path:
    required: false
    default: 'docker/Dockerfile'
    description: 'The path to the dockerfile.'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/${{ inputs.image-name }}
        flavor: |
          latest=true

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: '{{defaultContext}}:${{ inputs.docker-context }}'
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ inputs.image-name}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
