name: Publish Docker Image

on:
  push:
    branches: ['publish-container-image']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Build and Publish Simulator Image
        uses: terawatt-infrastructure/e-mobility-charging-stations-simulator/.github/actions/publish-image@publish-container-image
        with:
          image-name: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Web UI Image
        uses: terawatt-infrastructure/e-mobility-charging-stations-simulator/.github/actions/publish-image@publish-container-image
        with:
          image-name: ${{ github.repository }}-webui
          docker-context: 'ui/web'
          github-token: ${{ secrets.GITHUB_TOKEN }}
